package main.java.edu.ucsi.gym;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Fares
 */
public class Booking extends javax.swing.JFrame {
    Connection con;
    ResultSet rs;
    PreparedStatement pst;
    String sessions;
    /**
     * Creates new form Booking
     */
    public boolean checker(){
        try{
            con = SQLConnection.ConnectorDb();

            Statement st = con.createStatement();
            String sql = "Select sessions from gymapp.users Where email ='"+em+"';";
            System.out.println("Checking Sessions"+ sql);

            rs = st.executeQuery(sql);
            System.out.println("Checking Sessions"+ sql);

            while(rs.next()){
                sessions = String.valueOf(rs.getString("sessions"));
            }
            st.close();
            if("0".equals(sessions)){
            return true;
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Checking Number of Sessions has failed." + e);
        }
        if("0".equals(sessions)){
            return true;
        }
        return false;
    }
    public Booking(String email) {
        super("Booking");
        initComponents();
        em = email;
        System.out.println("Starting Booking:" + em);
        Icon trainer1 = imgTrn1.getIcon();
        ImageIcon icon1 = (ImageIcon)trainer1;
        Icon trainer2 = imgTrn6.getIcon();
        ImageIcon icon2 = (ImageIcon)trainer2;
        Icon trainer3 = imgTrn3.getIcon();
        ImageIcon icon3 = (ImageIcon)trainer3;
        Icon trainer4 = imgTrn5.getIcon();
        ImageIcon icon4 = (ImageIcon)trainer4;
        Icon trainer5 = imgTrn2.getIcon();
        ImageIcon icon5 = (ImageIcon)trainer5;
        Icon trainer6 = imgTrn4.getIcon();
        ImageIcon icon6 = (ImageIcon)trainer6;
        
        Image img1 = icon1.getImage().getScaledInstance(200, 239, Image.SCALE_SMOOTH);
        imgTrn1.setIcon(new ImageIcon(img1));

        Image img2 = icon2.getImage().getScaledInstance(200, 239, Image.SCALE_SMOOTH);
        imgTrn6.setIcon(new ImageIcon(img2));

        Image img3 = icon3.getImage().getScaledInstance(200, 239, Image.SCALE_SMOOTH);
        imgTrn3.setIcon(new ImageIcon(img3));
        
        Image img4 = icon4.getImage().getScaledInstance(200, 239, Image.SCALE_SMOOTH);
        imgTrn5.setIcon(new ImageIcon(img4));
        
        Image img5 = icon5.getImage().getScaledInstance(200, 239, Image.SCALE_SMOOTH);
        imgTrn2.setIcon(new ImageIcon(img5));
        
        Image img6 = icon6.getImage().getScaledInstance(200, 239, Image.SCALE_SMOOTH);
        imgTrn4.setIcon(new ImageIcon(img6));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        BookingPanel = new javax.swing.JPanel();
        imgTrn1 = new javax.swing.JLabel();
        imgTrn6 = new javax.swing.JLabel();
        imgTrn3 = new javax.swing.JLabel();
        imgTrn2 = new javax.swing.JLabel();
        imgTrn4 = new javax.swing.JLabel();
        imgTrn5 = new javax.swing.JLabel();
        btnDiet = new javax.swing.JButton();
        btnPayment = new javax.swing.JButton();
        btnBooking = new javax.swing.JButton();
        Alex = new javax.swing.JLabel();
        Amanda = new javax.swing.JLabel();
        Jake = new javax.swing.JLabel();
        Adam = new javax.swing.JLabel();
        Trevor = new javax.swing.JLabel();
        Arnold = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        btnProfile = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnOptions = new javax.swing.JButton();
        btnBookings = new javax.swing.JButton();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BookingPanel.setBackground(new java.awt.Color(255, 255, 255));
        BookingPanel.setPreferredSize(new java.awt.Dimension(1259, 708));

        imgTrn1.setIcon(new javax.swing.ImageIcon("C:\\Education\\UCSI Y2S1\\Business Systems Development Tools\\Assignment\\netbeans\\Gym\\Resources\\Trainer1.png")); // NOI18N
        imgTrn1.setToolTipText("");
        imgTrn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imgTrn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgTrn1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                imgTrn1MouseEntered(evt);
            }
        });

        imgTrn6.setIcon(new javax.swing.ImageIcon("C:\\Education\\UCSI Y2S1\\Business Systems Development Tools\\Assignment\\netbeans\\Gym\\Resources\\Trainer6.png")); // NOI18N
        imgTrn6.setToolTipText("");
        imgTrn6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imgTrn6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgTrn6MouseClicked(evt);
            }
        });

        imgTrn3.setIcon(new javax.swing.ImageIcon("C:\\Education\\UCSI Y2S1\\Business Systems Development Tools\\Assignment\\netbeans\\Gym\\Resources\\Trainer3.png")); // NOI18N
        imgTrn3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imgTrn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgTrn3MouseClicked(evt);
            }
        });

        imgTrn2.setIcon(new javax.swing.ImageIcon("C:\\Education\\UCSI Y2S1\\Business Systems Development Tools\\Assignment\\netbeans\\Gym\\Resources\\Trainer2.png")); // NOI18N
        imgTrn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imgTrn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgTrn2MouseClicked(evt);
            }
        });

        imgTrn4.setIcon(new javax.swing.ImageIcon("C:\\Education\\UCSI Y2S1\\Business Systems Development Tools\\Assignment\\netbeans\\Gym\\Resources\\Trainer4.png")); // NOI18N
        imgTrn4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imgTrn4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgTrn4MouseClicked(evt);
            }
        });

        imgTrn5.setIcon(new javax.swing.ImageIcon("C:\\Education\\UCSI Y2S1\\Business Systems Development Tools\\Assignment\\netbeans\\Gym\\Resources\\Trainer5.png")); // NOI18N
        imgTrn5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imgTrn5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgTrn5MouseClicked(evt);
            }
        });

        btnDiet.setBackground(new java.awt.Color(0, 0, 0));
        btnDiet.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnDiet.setForeground(new java.awt.Color(255, 255, 255));
        btnDiet.setText("Diet Plan");
        btnDiet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDiet.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDiet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDietMouseClicked(evt);
            }
        });

        btnPayment.setBackground(new java.awt.Color(0, 0, 0));
        btnPayment.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnPayment.setForeground(new java.awt.Color(255, 255, 255));
        btnPayment.setText("Membership");
        btnPayment.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPayment.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPayment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPaymentMouseClicked(evt);
            }
        });

        btnBooking.setBackground(new java.awt.Color(0, 0, 0));
        btnBooking.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnBooking.setForeground(new java.awt.Color(255, 255, 255));
        btnBooking.setText("Booking");
        btnBooking.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBooking.setEnabled(false);
        btnBooking.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookingActionPerformed(evt);
            }
        });

        Alex.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Alex.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Alex.setText("Alex");

        Amanda.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Amanda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Amanda.setText("Amanda");

        Jake.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Jake.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Jake.setText("Jake");

        Adam.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Adam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Adam.setText("Adam");

        Trevor.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Trevor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Trevor.setText("Trevor");

        Arnold.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Arnold.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Arnold.setText("Arnold");

        btnLogout.setBackground(new java.awt.Color(0, 0, 0));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.setEnabled(false);
        btnLogout.setMaximumSize(new java.awt.Dimension(73, 36));
        btnLogout.setMinimumSize(new java.awt.Dimension(73, 36));
        btnLogout.setPreferredSize(new java.awt.Dimension(73, 36));
        btnLogout.setVisible(false);
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
        });
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnProfile.setBackground(new java.awt.Color(0, 0, 0));
        btnProfile.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnProfile.setForeground(new java.awt.Color(255, 255, 255));
        btnProfile.setText("Profile");
        btnProfile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProfile.setEnabled(false);
        btnProfile.setMaximumSize(new java.awt.Dimension(73, 36));
        btnProfile.setMinimumSize(new java.awt.Dimension(73, 36));
        btnProfile.setPreferredSize(new java.awt.Dimension(73, 36));
        btnProfile.setVisible(false);
        btnProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProfileMouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Book Trainer");

        btnOptions.setBackground(new java.awt.Color(101, 101, 101));
        btnOptions.setForeground(new java.awt.Color(255, 255, 255));
        btnOptions.setIcon(new javax.swing.ImageIcon("C:\\Education\\UCSI Y2S1\\Business Systems Development Tools\\Assignment\\netbeans\\Gym\\Resources\\user.png")); // NOI18N
        btnOptions.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOptions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOptionsMouseClicked(evt);
            }
        });
        btnOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOptionsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(423, 423, 423)
                .addComponent(btnOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnOptions)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        btnBookings.setBackground(new java.awt.Color(0, 0, 0));
        btnBookings.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBookings.setForeground(new java.awt.Color(255, 255, 255));
        btnBookings.setText("Schedule");
        btnBookings.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBookings.setEnabled(false);
        btnBookings.setMaximumSize(new java.awt.Dimension(73, 36));
        btnBookings.setMinimumSize(new java.awt.Dimension(73, 36));
        btnBookings.setPreferredSize(new java.awt.Dimension(73, 36));
        btnBookings.setVisible(false);
        btnBookings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBookingsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BookingPanelLayout = new javax.swing.GroupLayout(BookingPanel);
        BookingPanel.setLayout(BookingPanelLayout);
        BookingPanelLayout.setHorizontalGroup(
            BookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookingPanelLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(BookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Adam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(imgTrn4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Alex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(imgTrn1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(214, 214, 214)
                .addGroup(BookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Trevor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(imgTrn5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Amanda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(imgTrn2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(212, 212, 212)
                .addGroup(BookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgTrn6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Arnold, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(imgTrn3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Jake, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addGroup(BookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBookings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(BookingPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(BookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BookingPanelLayout.createSequentialGroup()
                        .addComponent(btnBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btnPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btnDiet, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        BookingPanelLayout.setVerticalGroup(
            BookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BookingPanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(BookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BookingPanelLayout.createSequentialGroup()
                        .addComponent(imgTrn2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Amanda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(imgTrn5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Trevor)
                        .addGap(27, 27, 27))
                    .addGroup(BookingPanelLayout.createSequentialGroup()
                        .addGroup(BookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BookingPanelLayout.createSequentialGroup()
                                .addGroup(BookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(imgTrn3, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(BookingPanelLayout.createSequentialGroup()
                                        .addComponent(btnProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)
                                        .addComponent(btnBookings, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, 0)
                                .addComponent(Jake)
                                .addGap(18, 18, 18)
                                .addComponent(imgTrn6, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Arnold))
                            .addGroup(BookingPanelLayout.createSequentialGroup()
                                .addComponent(imgTrn1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Alex)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(imgTrn4, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Adam)))
                        .addGap(21, 21, 21)))
                .addGroup(BookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDiet, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BookingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BookingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1261, 745));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBookingActionPerformed

    private void imgTrn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgTrn1MouseClicked
        // TODO add your handling code here:
        if(checker()){
            JOptionPane.showMessageDialog(this, "You used all your 4 training sessions!");
            return;
        }
        setVisible(false);
        Trainer load = new Trainer(1,em);
        load.setVisible(true);
    }//GEN-LAST:event_imgTrn1MouseClicked

    private void imgTrn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgTrn2MouseClicked
        // TODO add your handling code here:
        if(checker()){
            JOptionPane.showMessageDialog(this, "You used all your 4 training sessions!");
            return;
        }
        setVisible(false);
        Trainer load = new Trainer(2,em);
        load.setVisible(true);
    }//GEN-LAST:event_imgTrn2MouseClicked

    private void imgTrn3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgTrn3MouseClicked
        // TODO add your handling code here:
                if(checker()){
            JOptionPane.showMessageDialog(this, "You used all your 4 training sessions!");
            return;
        }
        setVisible(false);
        Trainer load = new Trainer(3,em);
        load.setVisible(true);

    }//GEN-LAST:event_imgTrn3MouseClicked

    private void imgTrn4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgTrn4MouseClicked
        // TODO add your handling code here:
        if(checker()){
            JOptionPane.showMessageDialog(this, "You used all your 4 training sessions!");
            return;
        }
        setVisible(false);
        Trainer load = new Trainer(4,em);
        load.setVisible(true);

    }//GEN-LAST:event_imgTrn4MouseClicked

    private void imgTrn5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgTrn5MouseClicked
        // TODO add your handling code here:
        if(checker()){
            JOptionPane.showMessageDialog(this, "You used all your 4 training sessions!");
            return;
        }
        setVisible(false);
        Trainer load = new Trainer(5,em);
        load.setVisible(true);
    }//GEN-LAST:event_imgTrn5MouseClicked

    private void imgTrn6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgTrn6MouseClicked
        // TODO add your handling code here:
        if(checker()){
            JOptionPane.showMessageDialog(this, "You used all your 4 training sessions!");
            return;
        }
        setVisible(false);
        Trainer load = new Trainer(6,em);
        load.setVisible(true);
    }//GEN-LAST:event_imgTrn6MouseClicked

    private void btnOptionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOptionsMouseClicked
        // TODO add your handling code here:
        if (btnProfile.isEnabled()){
            btnProfile.setEnabled(false);
            btnProfile.setVisible(false);
            btnLogout.setEnabled(false);
            btnLogout.setVisible(false);
            btnBookings.setVisible(false);
            btnBookings.setEnabled(false);
            return;
        }
        btnProfile.setEnabled(true);
        btnProfile.setVisible(true);
        btnLogout.setEnabled(true);
        btnLogout.setVisible(true);
        btnBookings.setEnabled(true);
        btnBookings.setVisible(true);
    }//GEN-LAST:event_btnOptionsMouseClicked

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        // TODO add your handling code here:
        Login load = new Login();
        setVisible(false);
        load.setVisible(true);
    }//GEN-LAST:event_btnLogoutMouseClicked

    private void btnPaymentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPaymentMouseClicked
        // TODO add your handling code here:
        Membership load = new Membership(em);
        setVisible(false);
        load.setVisible(true);

    }//GEN-LAST:event_btnPaymentMouseClicked

    private void btnDietMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDietMouseClicked
        // TODO add your handling code here:
        Interface load = new Interface(em);
        setVisible(false);
        load.setVisible(true);
    }//GEN-LAST:event_btnDietMouseClicked

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOptionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOptionsActionPerformed

    private void btnBookingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBookingsMouseClicked
        // TODO add your handling code here:
        Schedule load = new Schedule(em);
        setVisible(false);
        load.setVisible(true);

    }//GEN-LAST:event_btnBookingsMouseClicked

    private void btnProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProfileMouseClicked
        // TODO add your handling code here:
        Profile load = new Profile(em);
        setVisible(false);
        load.setVisible(true);
    }//GEN-LAST:event_btnProfileMouseClicked

    private void imgTrn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgTrn1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_imgTrn1MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Booking("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Adam;
    private javax.swing.JLabel Alex;
    private javax.swing.JLabel Amanda;
    private javax.swing.JLabel Arnold;
    private javax.swing.JPanel BookingPanel;
    private javax.swing.JLabel Jake;
    private javax.swing.JLabel Trevor;
    private javax.swing.JButton btnBooking;
    private javax.swing.JButton btnBookings;
    private javax.swing.JButton btnDiet;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnOptions;
    private javax.swing.JButton btnPayment;
    private javax.swing.JButton btnProfile;
    private javax.swing.JLabel imgTrn1;
    private javax.swing.JLabel imgTrn2;
    private javax.swing.JLabel imgTrn3;
    private javax.swing.JLabel imgTrn4;
    private javax.swing.JLabel imgTrn5;
    private javax.swing.JLabel imgTrn6;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    public String em;

}
