/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.java.edu.ucsi.gym;

import com.toedter.calendar.JDateChooser;
import java.util.Date;
import java.awt.Image;
import java.sql.*;
import java.text.ParseException;
import java.time.LocalDate;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
/**
 *
 * @author Fares
 */
public class Membership extends javax.swing.JFrame {
    Connection con;
    ResultSet rs;
    PreparedStatement pst;
    String em;
    String status;

    public Membership(String email) {
        initComponents();
        em = email;
        System.out.println(em);
        Icon logo = imgmembership.getIcon();
        ImageIcon icon1 = (ImageIcon)logo;
        Image img = icon1.getImage().getScaledInstance(434, 460, Image.SCALE_SMOOTH);
        imgmembership.setIcon(new ImageIcon(img));
        cardNumber.getDocument().addDocumentListener(new DocumentListener() {
        @Override
        public void changedUpdate(DocumentEvent e) {
          warn();
        }
        @Override
        public void removeUpdate(DocumentEvent e) {
            warn();

        }
        @Override
        public void insertUpdate(DocumentEvent e) {
            warn();
        }

        public void warn() {
            String str = cardNumber.getText();
            long x = 0;
            
            boolean check = true;
                if(cardNumber.getText().isEmpty() || cardNumber.getText().isBlank() || cardNumber.getText() == ""){
                    imgCard.setIcon(new javax.swing.ImageIcon("C:\\Education\\UCSI Y2S1\\Business Systems Development Tools\\Assignment\\netbeans\\Gym\\Resources\\white.png"));
                    Icon logo2 = imgCard.getIcon();
                    ImageIcon icon = (ImageIcon)logo2;
                    Image img2 = icon.getImage().getScaledInstance(100, 50, Image.SCALE_SMOOTH);
                    imgCard.setIcon(new ImageIcon(img2));
                }else{
                try{
                    x = Long.parseLong(str);

                }catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Come on... Enter Numbers!");
                    return;
                }
                while (x > 9) {
                x /= 10;
                }
                if (x == 4){
                    imgCard.setIcon(new javax.swing.ImageIcon("C:\\Education\\UCSI Y2S1\\Business Systems Development Tools\\Assignment\\netbeans\\Gym\\Resources\\visa.png"));
                    Icon logo2 = imgCard.getIcon();
                    ImageIcon icon = (ImageIcon)logo2;
                    Image img2 = icon.getImage().getScaledInstance(100, 50, Image.SCALE_SMOOTH);
                    imgCard.setIcon(new ImageIcon(img2));
                }
                else if(x == 5){
                    imgCard.setIcon(new javax.swing.ImageIcon("C:\\Education\\UCSI Y2S1\\Business Systems Development Tools\\Assignment\\netbeans\\Gym\\Resources\\mastercard.png"));
                    Icon logo2 = imgCard.getIcon();
                    ImageIcon icon = (ImageIcon)logo2;
                    Image img2 = icon.getImage().getScaledInstance(100, 50, Image.SCALE_SMOOTH);
                    imgCard.setIcon(new ImageIcon(img2));
                }
                else if(x != 5 && x != 4){
                    JOptionPane.showMessageDialog(null, "Visa & MasterCard Only!");
                }
                }


           }
        
      });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnOptions = new javax.swing.JButton();
        btnProfile = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        imgmembership = new javax.swing.JLabel();
        lblCard = new javax.swing.JLabel();
        pay = new javax.swing.JButton();
        btnPayment = new javax.swing.JButton();
        btnBooking = new javax.swing.JButton();
        btnDiet = new javax.swing.JButton();
        lblCvv = new javax.swing.JLabel();
        cardDate = new com.toedter.calendar.JDateChooser();
        lblCardDate = new javax.swing.JLabel();
        cvvNumber = new javax.swing.JTextField();
        imgCard = new javax.swing.JLabel();
        cardNumber = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Membership");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnOptions.setBackground(new java.awt.Color(255, 255, 255));
        btnOptions.setForeground(new java.awt.Color(255, 255, 255));
        btnOptions.setIcon(new javax.swing.ImageIcon("C:\\Education\\UCSI Y2S1\\Business Systems Development Tools\\Assignment\\netbeans\\Gym\\Resources\\user.png")); // NOI18N
        btnOptions.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOptions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOptionsMouseClicked(evt);
            }
        });

        btnProfile.setBackground(new java.awt.Color(0, 0, 0));
        btnProfile.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnProfile.setForeground(new java.awt.Color(255, 255, 255));
        btnProfile.setText("Profile");
        btnProfile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProfile.setEnabled(false);
        btnProfile.setVisible(false);
        btnProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProfileMouseClicked(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(0, 0, 0));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.setEnabled(false);
        btnLogout.setVisible(false);
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnProfile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btnOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        imgmembership.setIcon(new javax.swing.ImageIcon("C:\\Education\\UCSI Y2S1\\Business Systems Development Tools\\Assignment\\netbeans\\Gym\\Resources\\membership.png")); // NOI18N
        imgmembership.setToolTipText("");

        lblCard.setBackground(java.awt.Color.black);
        lblCard.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblCard.setText("Enter Card Number:");

        pay.setBackground(new java.awt.Color(0, 0, 0));
        pay.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        pay.setForeground(new java.awt.Color(255, 255, 255));
        pay.setText("Pay RM250");
        pay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                payMouseClicked(evt);
            }
        });
        pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payActionPerformed(evt);
            }
        });

        btnPayment.setBackground(new java.awt.Color(0, 0, 0));
        btnPayment.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnPayment.setForeground(new java.awt.Color(255, 255, 255));
        btnPayment.setText("Membership");
        btnPayment.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPayment.setEnabled(false);
        btnPayment.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnBooking.setBackground(new java.awt.Color(0, 0, 0));
        btnBooking.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnBooking.setForeground(new java.awt.Color(255, 255, 255));
        btnBooking.setText("Booking");
        btnBooking.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBooking.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookingActionPerformed(evt);
            }
        });

        btnDiet.setBackground(new java.awt.Color(0, 0, 0));
        btnDiet.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnDiet.setForeground(new java.awt.Color(255, 255, 255));
        btnDiet.setText("Diet Plan");
        btnDiet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDiet.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDiet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDietMouseClicked(evt);
            }
        });

        lblCvv.setBackground(java.awt.Color.black);
        lblCvv.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblCvv.setText("CVV Number:");

        cardDate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cardDate.setMinSelectableDate(new Date());
        cardDate.setDateFormatString("dd-MM-yyyy");

        lblCardDate.setBackground(java.awt.Color.black);
        lblCardDate.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblCardDate.setText("Expiry Date:");

        cvvNumber.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cvvNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cvvNumberActionPerformed(evt);
            }
        });

        cardNumber.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cardNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardNumberActionPerformed(evt);
            }
        });
        cardNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cardNumberKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cardNumber)
                                .addComponent(lblCard))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(imgCard, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cardDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCardDate, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))
                            .addGap(55, 55, 55)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cvvNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblCvv))))
                    .addComponent(pay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDiet, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblTitle)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(imgmembership, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imgmembership, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblCard, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(imgCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cardNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCvv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCardDate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cardDate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cvvNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addComponent(pay, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDiet, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1271, 745));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOptionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOptionsMouseClicked
        // TODO add your handling code here:
        if (btnProfile.isEnabled()){
            btnProfile.setEnabled(false);
            btnProfile.setVisible(false);
            btnLogout.setEnabled(false);
            btnLogout.setVisible(false);
            return;
        }
        btnProfile.setEnabled(true);
        btnProfile.setVisible(true);
        btnLogout.setEnabled(true);
        btnLogout.setVisible(true);
    }//GEN-LAST:event_btnOptionsMouseClicked

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        Login load = new Login();
        load.setVisible(true);
    }//GEN-LAST:event_btnLogoutMouseClicked

    private void btnBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookingActionPerformed
        // TODO add your handling code here:
        try{
            con = SQLConnection.ConnectorDb();

            Statement st = con.createStatement();
            String sql = "Select status from gymapp.users Where email ='"+em+"';";
            rs = st.executeQuery(sql);
            System.out.println(sql);

            while(rs.next()){
                status = String.valueOf(rs.getString("status"));
            }
            con.close();
        }catch(Exception e){
            System.out.println(e);
        }

        if("1".equals(status)){
            Booking load = new Booking(em);
            setVisible(false);
            load.setVisible(true);
        }else if("0".equals(status)){
            JOptionPane.showMessageDialog(this, "Please Buy Membership First!");
        }
    }//GEN-LAST:event_btnBookingActionPerformed

    private void cvvNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cvvNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cvvNumberActionPerformed

    private void cardNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardNumberActionPerformed

    private void cardNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cardNumberKeyTyped
        // TODO add your handling code here:
        if (cardNumber.getText().length() >= 16){
            evt.consume();
        }
    }//GEN-LAST:event_cardNumberKeyTyped

    private void payMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payMouseClicked
        // TODO add your handling code here:
        Date date;
        date = cardDate.getDate();

        if(cardNumber.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Missing Card Number");
                return;
        }
        else if(date == null){
            JOptionPane.showMessageDialog(this, "Missing Date");
            return;
        }
        
        else if(cvvNumber.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Missing CVV Number");
            return;

        }
        else{
            try{
                con = SQLConnection.ConnectorDb();
                String sql= "Update gymapp.users SET status = 1 WHERE email ='"+em+"';";
                System.out.println(sql);
                pst = con.prepareStatement(sql);
                System.out.println(pst);
                pst.execute();                
                JOptionPane.showMessageDialog(null, "Congratulations!\nYou are a member now!");
                con.close();
            }
            catch(Exception ex){
                JOptionPane.showMessageDialog(this, ex);
            }
        }
    }//GEN-LAST:event_payMouseClicked

    private void payActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_payActionPerformed

    private void btnProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProfileMouseClicked
        // TODO add your handling code here:
        Profile load = new Profile(em);
        setVisible(false);
        load.setVisible(true);
    }//GEN-LAST:event_btnProfileMouseClicked

    private void btnDietMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDietMouseClicked
        // TODO add your handling code here:
        Interface load = new Interface(em);
        setVisible(false);
        load.setVisible(true);

    }//GEN-LAST:event_btnDietMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Membership.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Membership.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Membership.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Membership.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Membership("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBooking;
    private javax.swing.JButton btnDiet;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnOptions;
    private javax.swing.JButton btnPayment;
    private javax.swing.JButton btnProfile;
    private com.toedter.calendar.JDateChooser cardDate;
    private javax.swing.JTextField cardNumber;
    private javax.swing.JTextField cvvNumber;
    private javax.swing.JLabel imgCard;
    private javax.swing.JLabel imgmembership;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCard;
    private javax.swing.JLabel lblCardDate;
    private javax.swing.JLabel lblCvv;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JButton pay;
    // End of variables declaration//GEN-END:variables
}
