/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.java.edu.ucsi.gym;
import com.toedter.calendar.JDateChooser;
import java.util.Date;
import java.awt.Color;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.ColorUIResource;

/**
 *
 * @author Fares
 */
public class Trainer extends javax.swing.JFrame {
    Connection con;
    ResultSet rs;
    PreparedStatement pst;
    String em;
    String trainerName;
    /**
     * Creates new form Trainer
     */
    public Trainer(int ID, String email) {
        super("Trainer");
        initComponents();
        em = email;
        System.out.println("Starting Trainer:" + em);
        con = SQLConnection.ConnectorDb();
        if (ID ==1){
            trainerName = "Alex";
            trnName.setText("Alex");
            imgTrn.setIcon(new javax.swing.ImageIcon("C:\\Education\\UCSI Y2S1\\Business Systems Development Tools\\Assignment\\netbeans\\Gym\\Resources\\Trainer1.png")); // NOI18N
            imgTrn.setToolTipText("");
            imgTrn.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        }
        else if (ID ==2){
            trainerName = "Amanda";
            trnName.setText("Amanda");
            imgTrn.setIcon(new javax.swing.ImageIcon("C:\\Education\\UCSI Y2S1\\Business Systems Development Tools\\Assignment\\netbeans\\Gym\\Resources\\Trainer2.png")); // NOI18N
        }
        else if (ID ==3){
            trainerName = "Jake";
            trnName.setText("Jake");
            imgTrn.setIcon(new javax.swing.ImageIcon("C:\\Education\\UCSI Y2S1\\Business Systems Development Tools\\Assignment\\netbeans\\Gym\\Resources\\Trainer3.png")); // NOI18N
        }
        else if (ID ==4){
            trainerName = "Adam";
            trnName.setText("Adam");
            imgTrn.setIcon(new javax.swing.ImageIcon("C:\\Education\\UCSI Y2S1\\Business Systems Development Tools\\Assignment\\netbeans\\Gym\\Resources\\Trainer4.png")); // NOI18N
        }
        else if (ID ==5){
            trainerName = "Trevor";
            trnName.setText("Trevor");
            imgTrn.setIcon(new javax.swing.ImageIcon("C:\\Education\\UCSI Y2S1\\Business Systems Development Tools\\Assignment\\netbeans\\Gym\\Resources\\Trainer5.png")); // NOI18N
        }
        else if (ID ==6){
            trainerName = "Arnold";
            trnName.setText("Arnold");
            imgTrn.setIcon(new javax.swing.ImageIcon("C:\\Education\\UCSI Y2S1\\Business Systems Development Tools\\Assignment\\netbeans\\Gym\\Resources\\Trainer6.png")); // NOI18N
            imgTrn.setToolTipText("");
            imgTrn.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        }
        Icon trainer1 = imgTrn.getIcon();
        ImageIcon icon1 = (ImageIcon)trainer1;
        Image img1 = icon1.getImage().getScaledInstance(515, 708, Image.SCALE_SMOOTH);
        imgTrn.setIcon(new ImageIcon(img1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TrainerPanel = new javax.swing.JPanel();
        imgTrn = new javax.swing.JLabel();
        trnName = new javax.swing.JLabel();
        lblTrnname = new javax.swing.JLabel();
        btnBook = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        trnSum = new javax.swing.JLabel();
        bookingDate = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TrainerPanel.setBackground(new java.awt.Color(255, 255, 255));
        TrainerPanel.setPreferredSize(new java.awt.Dimension(1259, 708));

        imgTrn.setBackground(new java.awt.Color(255, 255, 255));
        imgTrn.setIcon(new javax.swing.ImageIcon("C:\\Education\\UCSI Y2S1\\Business Systems Development Tools\\Assignment\\netbeans\\Gym\\Resources\\Trainer2.png")); // NOI18N
        imgTrn.setToolTipText("");
        imgTrn.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        trnName.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        trnName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        trnName.setText("Name");

        lblTrnname.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        lblTrnname.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTrnname.setText("Hi! My name is");

        btnBook.setBackground(new java.awt.Color(0, 0, 0));
        btnBook.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBook.setForeground(new java.awt.Color(255, 255, 255));
        btnBook.setText("Book");
        btnBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBookMouseClicked(evt);
            }
        });
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(0, 0, 0));
        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Booking Date:");

        trnSum.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        trnSum.setToolTipText("");
        trnSum.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        trnSum.setText("<html>"+"Professional Summary:<br />"+"Spirited Personal Fitness Trainer with weight management expertise<br />"+"and ability to motivate others toward accomplishing weight loss goals. <br />"+"Designs classes to match skill and learning levels of all participants. <br />"+"Skilled in personal program development and individual life and body assessments."+"<br /><br />"+"Skills:<br />"+"-Fitness instruction<br />"+"-Health and wellness<br />"+"-Exercise program design <br />"+"-Coaching<br />"+"-Knowledge of human anatomy<br />"+"-Nutrition principles<br />"+"-Weight management<br />"+"</html>");

        bookingDate.setMinSelectableDate(new Date());
        bookingDate.setDateFormatString("dd-MM-yyyy");
        bookingDate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        javax.swing.GroupLayout TrainerPanelLayout = new javax.swing.GroupLayout(TrainerPanel);
        TrainerPanel.setLayout(TrainerPanelLayout);
        TrainerPanelLayout.setHorizontalGroup(
            TrainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TrainerPanelLayout.createSequentialGroup()
                .addGroup(TrainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TrainerPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(TrainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TrainerPanelLayout.createSequentialGroup()
                                .addComponent(lblTrnname)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(trnName))
                            .addGroup(TrainerPanelLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bookingDate, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 343, Short.MAX_VALUE))
                    .addGroup(TrainerPanelLayout.createSequentialGroup()
                        .addComponent(btnBook, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TrainerPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(trnSum, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)))
                .addComponent(imgTrn, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        TrainerPanelLayout.setVerticalGroup(
            TrainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TrainerPanelLayout.createSequentialGroup()
                .addGroup(TrainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTrnname)
                    .addComponent(trnName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(trnSum, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(TrainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(bookingDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(TrainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBook, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(imgTrn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TrainerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TrainerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(1273, 745));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBookActionPerformed

    private void btnBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBookMouseClicked
        // TODO add your handling code here:
         try{
             SimpleDateFormat Date_Format = new SimpleDateFormat("yyyy-MM-dd"); 
             
             String date=""+Date_Format.format(bookingDate.getDate());

                    String sql= "insert into gymapp.bookings (userEmail, trainerName, bookingDate) values(?,?,?);";
                    pst = con.prepareStatement(sql);
                    pst.setString(1,  em);
                    pst.setString(2, trainerName);
                    pst.setString(3, date);
                    pst.execute();                
                    System.out.println(pst);

                    JOptionPane.showMessageDialog(null, "Booking Completed");
                    sql= "Update gymapp.users SET sessions = sessions-1 WHERE email ='"+em+"';";
                    pst = con.prepareStatement(sql);
                    System.out.println(pst);
                    pst.execute();                
                    con.close();
            }
                catch(Exception ex){
                    JOptionPane.showMessageDialog(this, ex);
                }
        Booking load = new Booking(em);
        setVisible(false);
        load.setVisible(true);

    }//GEN-LAST:event_btnBookMouseClicked

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        // TODO add your handling code here:
        Booking load = new Booking(em);
        setVisible(false);
        load.setVisible(true);

    }//GEN-LAST:event_btnCancelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Trainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Trainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Trainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Trainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Trainer(0,"").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel TrainerPanel;
    private com.toedter.calendar.JDateChooser bookingDate;
    private javax.swing.JButton btnBook;
    private javax.swing.JButton btnCancel;
    private javax.swing.JLabel imgTrn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblTrnname;
    private javax.swing.JLabel trnName;
    private javax.swing.JLabel trnSum;
    // End of variables declaration//GEN-END:variables
}
